Veri Tipleri: Liste

In [1]:
liste = ["elma", "armut", "muz"]
liste

['elma', 'armut', 'muz']

In [3]:
liste_fiyat = [10, 20, 30]
liste_fiyat
print(liste_fiyat)

[10, 20, 30]


In [4]:
type(liste_fiyat)

list

In [5]:
hafta_liste = ["pazartesi", "sali", "carsamba", "persembe", "cuma", "cumartesi", "pazar"]
hafta_liste

['pazartesi', 'sali', 'carsamba', 'persembe', 'cuma', 'cumartesi', 'pazar']

In [7]:
len(hafta_liste)

7

In [6]:
# indeksleme
hafta_liste[0] # Listenin 0' inci indeksi

'pazartesi'

In [8]:
hafta_liste[len(hafta_liste)-1]

'pazar'

In [9]:
# "pazartesi", "sali", "carsamba", "persembe"
hafta_liste[0:4]

['pazartesi', 'sali', 'carsamba', 'persembe']

In [10]:
hafta_liste[:4]

['pazartesi', 'sali', 'carsamba', 'persembe']

In [12]:
hafta_liste[3:]

['persembe', 'cuma', 'cumartesi', 'pazar']

In [15]:
hafta_liste[3:7]

['persembe', 'cuma', 'cumartesi', 'pazar']

In [14]:
hafta_liste[-4:]

['persembe', 'cuma', 'cumartesi', 'pazar']

In [17]:
sayi_listesi = [1, 2, 3, 4, 5]
sayi_listesi

[1, 2, 3, 4, 5]

In [18]:
sayi_listesi.append(6)
sayi_listesi

[1, 2, 3, 4, 5, 6]

In [19]:
sayi_listesi.remove(6)
sayi_listesi

[1, 2, 3, 4, 5]

In [20]:
sayi_listesi.reverse() # Listeyi ters çevirme
sayi_listesi

[5, 4, 3, 2, 1]

In [21]:
sayi_listesi.sort() # Küçükten büyüğe sıralama
sayi_listesi

[1, 2, 3, 4, 5]

Veri Tipleri: Tuple

In [22]:
tuple_sayi = (1, 2, 3, 4, 5)
tuple_sayi

(1, 2, 3, 4, 5)

In [23]:
tuple_sayi[-2]

4

In [24]:
tuple_sayi[2:]

(3, 4, 5)

In [25]:
tuple_sayi.count(3) # Tuple icerisinde bulunan istedigimiz elemani sayma

1

In [29]:
liste_deneme = [1,3,2]
liste_deneme_sorted = sorted(liste_deneme) # kucukten buyuge siralama

In [30]:
print(liste_deneme)
print(liste_deneme_sorted)

[1, 3, 2]
[1, 2, 3]


Veri Tipleri: Dictionary

* anahtar-deger: key-value pair

In [32]:
dictionary = {"elma": 10, "armut": 20, "muz": "ankara"}
dictionary

{'elma': 10, 'armut': 20, 'muz': 'ankara'}

In [33]:
sehirler_plakalar = {"istanbul": 34, "ankara": 6, "izmir": 35}
sehirler_plakalar

{'istanbul': 34, 'ankara': 6, 'izmir': 35}

In [34]:
sehirler_plakalar.keys()

dict_keys(['istanbul', 'ankara', 'izmir'])

In [35]:
sehirler_plakalar.values()

dict_values([34, 6, 35])

In [36]:
sehirler_plakalar["istanbul"]

34

Veri Tipleri Dönüşümleri

In [37]:
metin = "16"
kesirlisayi = 10.5
tamsayi = 10

In [43]:
# str -> int
metin_int = int(metin)
print(metin_int)
type(metin_int)


16


int

In [44]:
# float -> str
kesirlisayi_str = str(kesirlisayi)
print(kesirlisayi_str)
type(kesirlisayi_str)

10.5


str

In [46]:
# int -> str
tamsayi_str = str(tamsayi)
print(tamsayi_str)
type(tamsayi_str)

10


str

In [48]:
# int -> float
tamsayi_float = float(tamsayi)
print(tamsayi_float)
type(tamsayi_float)

10.0


float

if - else

In [53]:
# eger sayi1 kucuktur sayi2 ise print(sayi1 kucuktur sayi2)
sayi1 = 12
sayi2 = 22

if sayi1 < sayi2: # eger True (dogru) ise if icerisine gir.
    print(f"sayi1: {sayi1} kucuktur sayi2: {sayi2}")
elif sayi2 < sayi1:
    print(f"sayi1: {sayi1} buyuktur sayi2: {sayi2}")
else:
  print("sayilar esit")

sayi1: 12 kucuktur sayi2: 22


In [54]:
sayi1 < sayi2

True

In [55]:
# problem: deger listenin icinde mi degil mi?
liste = [1, 2, 3, 4, 5]
deger = 3

if deger in liste:
    print(f"{deger} listenin icinde")
else:
    print(f"{deger} listenin icinde degil")

3 listenin icinde


In [56]:
# problem: ulke isimleri dictionary icerisinde var mi yok mu anlamaya calismak
dictionary = {"Turkiye": "Ankara", "Ingiltere": "Londra", "Almanya": "Berlin"}

keys = dictionary.keys()
print(keys)

dict_keys(['Turkiye', 'Ingiltere', 'Almanya'])


In [57]:
deger = "Ingiltere"

if deger in keys:
    print(f"{deger} dictionary icerisinde")
else:
    print(f"{deger} dictionary icerisinde degil")

Ingiltere dictionary icerisinde


In [ ]:
# liste = haftanın gunleri
# eger ptesi gunu listenin içerisinde 2.indekste ise print(ptesi gunu listenin ikinci indeksinde)

In [60]:
haftanin_gunleri = ["pazartesi", "sali", "carsamba", "persembe", "cuma", "cumartesi", "pazar"]
if "pazartesi" in haftanin_gunleri[2]:
    print("pazartesi listenin ikinci indeksinde")
else:
  print("degil")

degil


**for loop**

In [61]:
for i in range(1,11): # [1,2,3,4,5,6,7,8,9,10]
  print(i)

1
2
3
4
5
6
7
8
9
10


In [65]:
for i in range(1,11):
  print(i*2)

2
4
6
8
10
12
14
16
18
20


In [66]:
for i in ["pazartesi", "sali", "carsamba", "persembe", "cuma", "cumartesi", "pazar"]:
  print(i)

pazartesi
sali
carsamba
persembe
cuma
cumartesi
pazar


In [67]:
for i in "pazartesi sali": # string = karakter dizisi
  print(i)

p
a
z
a
r
t
e
s
i
 
s
a
l
i


In [72]:
liste = [1, 2, 3, 4, 5, 6, 7, 8, 9]
toplam = 0
for i in liste:
  toplam = toplam + i
print(toplam)
print(sum(liste))

45
45


In [73]:
"""
problem: NLP, elimizde str olarak cumle var. mesela: "Bugün Python Dersimiz Var."
["bugün", "python", "dersimiz", "var."]
"""
cumle = "Bugün Python Dersimiz Var."
cumle_liste = cumle.split()
print(cumle_liste)

['Bugün', 'Python', 'Dersimiz', 'Var.']


In [77]:
liste = []
for i in cumle_liste:
  kelime_kucuk_harf = i.lower()
  liste.append(kelime_kucuk_harf)
print(liste)

['bugün', 'python', 'dersimiz', 'var.']


In [ ]:
"""
problem: liste = [1,2,3,4,5,6]
fonksiyon
  girdi: liste
  ciktisi: listedeki cift sayilarin toplami
"""

In [81]:
def fonksiyon(liste):
  toplam = 0
  for i in liste:
    if i % 2 == 0:
      toplam = toplam + i
  return toplam

liste = [1,2,3,4,5,6]
print(fonksiyon(liste))

12


**While Loop**

In [82]:
i = 1
while i < 10:
  print(i)
  i = i + 1

1
2
3
4
5
6
7
8
9


In [84]:
# while ile toplama
liste = [1,2,3,4,5,6]
toplam = 0
i = 0
while (i < len(liste)): # len(liste) = 6
  toplam = toplam + liste[i]
  i = i + 1
print(toplam)

21


**Numpy**

In [85]:
import numpy as np


In [86]:
# numpy array olustur
liste = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
dizi = np.array(liste)
print(dizi)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [87]:
# array boyutu
dizi.shape # (15,) -> 15x1 lik vektor

(15,)

In [88]:
# 15x1 lik bir arrayi 3x5 lik bir matrise cevirelim
dizi2 = dizi.reshape(3,5)
dizi2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [89]:
print("shape: ", dizi2.shape)
print("dimension: ", dizi2.ndim)
print("data type: ", dizi2.dtype.name)
print("size: ", dizi2.size)
print("type: ", type(dizi2))

shape:  (3, 5)
dimension:  2
data type:  int64
size:  15
type:  <class 'numpy.ndarray'>


In [90]:
dizi2D = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
dizi2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [91]:
# sifirlardan olusan bir array olusturalim
sifir_dizi = np.zeros((3,4))
sifir_dizi

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [92]:
# birlerden olusan array
bir_dizi = np.ones((3,4))
bir_dizi

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [94]:
# bos bir array olustur
bos_dizi = np.empty((2,4))
bos_dizi

array([[4.79600735e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [95]:
# arange(x,y,basamak) x den baslar y ye kadar (y dahil degil) kadar gider basamak buyuklugunde artarak ilerler
# 10, 50, basamak = 5
dizi_aralik = np.arange(10,50,8)
dizi_aralik

array([10, 18, 26, 34, 42])

In [99]:
# linspace (x,y,basamak) x ve y(dahil) araliginda basamak kadar sayiya boler
dizi_bosluk = np.linspace(10,50,100)
print(dizi_bosluk)
len(dizi_bosluk)

[10.         10.4040404  10.80808081 11.21212121 11.61616162 12.02020202
 12.42424242 12.82828283 13.23232323 13.63636364 14.04040404 14.44444444
 14.84848485 15.25252525 15.65656566 16.06060606 16.46464646 16.86868687
 17.27272727 17.67676768 18.08080808 18.48484848 18.88888889 19.29292929
 19.6969697  20.1010101  20.50505051 20.90909091 21.31313131 21.71717172
 22.12121212 22.52525253 22.92929293 23.33333333 23.73737374 24.14141414
 24.54545455 24.94949495 25.35353535 25.75757576 26.16161616 26.56565657
 26.96969697 27.37373737 27.77777778 28.18181818 28.58585859 28.98989899
 29.39393939 29.7979798  30.2020202  30.60606061 31.01010101 31.41414141
 31.81818182 32.22222222 32.62626263 33.03030303 33.43434343 33.83838384
 34.24242424 34.64646465 35.05050505 35.45454545 35.85858586 36.26262626
 36.66666667 37.07070707 37.47474747 37.87878788 38.28282828 38.68686869
 39.09090909 39.49494949 39.8989899  40.3030303  40.70707071 41.11111111
 41.51515152 41.91919192 42.32323232 42.72727273 43

100

**Numpy Temel Operasyonları**

In [100]:
import numpy as np

In [101]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [104]:
print("Toplama: ", a+b)
print("Cikarma: ", a-b)
print("Carpma: ", a*b)
print("Bolme: ", a/b)
print("Dizinin kendisi ile carpimi: ", a**2)

Toplama:  [5 7 9]
Cikarma:  [-3 -3 -3]
Carpma:  [ 4 10 18]
Bolme:  [0.25 0.4  0.5 ]
Dizinin kendisi ile carpimi:  [1 4 9]


In [105]:
# filtreleme
a = np.array([1,2,3])
filtre = a < 2 # a array' nin icerisinde bulunan 2 den kucuk degerleri goster
filtre

array([ True, False, False])

In [106]:
# matris carpimi
a = np.array([1,2,3]) # 3x1
b = np.array([4,5,6]) # 3x1
a.dot(b)

32

In [107]:
a = np.array([[1,2,3],[3,4,5]]) # 2x3
b = np.array([[1,2,5],[3,4,6]]) # 2x3 -> T -> 3x2
a.dot(b.T)

array([[20, 29],
       [36, 55]])

In [108]:
a = np.array([[1,2,3], [4,5,6]])
print(sum(a))
print(np.sum(a))

[5 7 9]
21


In [109]:
print(a.max())
print(np.max(a))

6
6


In [110]:
print(a.min())
print(np.min(a))

1
1


In [111]:
# satir satir toplama
a.sum(axis=1)

array([ 6, 15])

In [112]:
# sutun sutun toplama
a.sum(axis=0)

array([5, 7, 9])

In [113]:
# karesi
np.square(a)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [116]:
# rastgele sayi uretme
np.random.random((3,3)) # normal dagilima gore 0-1

array([[0.59254375, 0.85624979, 0.66831559],
       [0.60528741, 0.79714226, 0.25140482],
       [0.48857001, 0.96737078, 0.34942424]])

In [118]:
rastgele_dizi = np.random.normal(0, 1, 5) # normal dagilima 0 ortalamali 1 std, 5 adet deger uret
rastgele_dizi

array([-0.27734754,  0.84474118, -2.0738965 , -1.7862291 , -0.77800872])

**indeksleme ve slicing**

In [151]:
import numpy as np

In [152]:
dizi = np.array([1,2,3,4,5,6,7])
dizi[3]

4

In [153]:
dizi[0:4]

array([1, 2, 3, 4])

In [154]:
dizi[:4]

array([1, 2, 3, 4])

In [155]:
# diziyi ters cevirme
dizi[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [156]:
dizi2D = np.array([[1,2,3,4,5],[6,7,8,9,10]])
dizi2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [157]:
dizi2D[1,2]

8

In [158]:
dizi2D[1, :] # : = hepsi sutun kismina yazdigim icin tum sutunlar demek

array([ 6,  7,  8,  9, 10])

In [163]:
dizi2D[:, 2] # : = hepsi satir kismina yazdigim icin tum satirlar demek

array([3, 8])

In [164]:
dizi2D[0, 0:2] # 1, 2

array([1, 2])

In [165]:
dizi2D[:, 2:4]
"""
[ 1,  2,  3,  4,  5],
[ 6,  7,  8,  9, 10]
"""


'\n[ 1,  2,  3,  4,  5],\n[ 6,  7,  8,  9, 10]\n'

In [166]:
dizi2D[-1, :]

array([ 6,  7,  8,  9, 10])

In [167]:
dizi2D[[0,1], [1,3]]

array([2, 9])

**Shape manipulation**

In [132]:
import numpy as np

In [133]:
dizi2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
dizi2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [136]:
dizi2D_shape = dizi2D.shape
dizi2D_shape

(3, 3)

In [138]:
dizi2D.reshape(dizi2D_shape[0]*dizi2D_shape[1],1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [139]:
dizi2D.reshape(dizi2D_shape[0]*dizi2D_shape[1],-1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
""""
[[1,2]
[3,4]]

reshape(4,-1)

[1,2,3,4]
"""

In [140]:
dizi2D.ravel() # düzleştirme # tensorflowda -> flatten

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [141]:
dizi2D.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
"""
1) A array = 2 boyutlu bir tane array -> (3,5)
2) B array = 1 boyutlu bir tane array -> (15,)
3) B array'ini (3,5) olacak sekilde reshape yapalim
4) C = A + B
5) D=linspace ve E=arange ile (3,5) lik matrisler olusturalim.
6) F = D + E
7) C'nin ve F' nin her bir elemanini for dongusu ile eleman eleman carpip G = (15,1) boyutunda elde edelim.
8) C ve F'yi (15,1) sonrasında C'nin ilk elemani ile F'nin son elemani toplayarak ilerleyelim.
9) toplam degerleri eger 1 den buyukse G1 isimli bir listeye atalim, else ise G2 isimli listeye atalim
"""

In [177]:
A = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
B = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
B = B.reshape(3,5)
C = A + B
print(C)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]


In [179]:
D = np.linspace(1,15,15).reshape(3,5)
E = np.arange(1,16).reshape(3,5)
F = D + E
print(F)

[[ 2.  4.  6.  8. 10.]
 [12. 14. 16. 18. 20.]
 [22. 24. 26. 28. 30.]]


In [186]:
G = []
for i in range(C.shape[0]): # 3 satirlari dolas
  for j in range(C.shape[1]): # 5 sutunları dolas
    G.append(C[i,j] * F[i,j])
print(np.array(G))

[  4.  16.  36.  64. 100. 144. 196. 256. 324. 400. 484. 576. 676. 784.
 900.]


In [194]:
C = C.reshape(15,1)
F = F.reshape(15,1)
F =F[::-1]
G1 = []
G2 = []
for i in range(len(C)):
    toplam = C[i] + F[i]
    if toplam > 1:
        G1.append(toplam)
    else:
        G2.append(toplam)
print(G1,G2)


[array([32.]), array([32.]), array([32.]), array([32.]), array([32.]), array([32.]), array([32.]), array([32.]), array([32.]), array([32.]), array([32.]), array([32.]), array([32.]), array([32.]), array([32.])] []
